mantel: schuhe handy pullover;
	@echo $@ anziehen
	@touch $@
schuhe:struempfe hose;
	@echo $@ anziehen
	@touch $@
handy: hose;
	@echo $@ anziehen
	@touch $@
pullover: hemd;
	@echo $@ anziehen
	@touch $@
struempfe:  ;
	@echo $@ anziehen
	@touch $@
hose: unterhose hemd;
	@echo $@ anziehen
	@touch $@
hemd: unterhemd;
	@echo $@ anziehen
	@touch $@
unterhose: ;
	@echo $@ anziehen
	@touch $@
unterhemd: ;
	@echo $@ anziehen
	@touch $@
nackt:
	rm -f mantel pullover handy schuhe hose hemd unterhemd unterhose struempfe
